[package]
name = "klondike-app"
version = "0.1.0"
description = "A Klondike Solitaire game implemented in Rust"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
eframe = "0.32.0"
egui = "0.32.0"
rand = "0.9.2"
